modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="chaosket"
version="0.0.3"
displayName="Chaosket"
displayURL="https://de.paul2craft.de"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Ian, Wuzuket"
description="Step into the realm of the Ethereal Forge, a comprehensive Minecraft mod that blends the finest aspects of technology and magic. Explore new biomes teeming with mystical mobs and exotic creatures. Master the art of arcane wizardry and uncover powerful wands and runes to keep your foes at bay or aid your ventures.  The Ethereal Forge allows you to construct complex machinery and automation systems that revolutionize your resource production. From simple tools to advanced devices harnessing energy from the elements themselves, this mod pushes the boundaries of your Minecraft experience."

[[dependencies.chaosket]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.chaosket]]
    modId="world_edit"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chaosket]]
    modId="use_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chaosket]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chaosket]]
    modId="create"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chaosket]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chaosket]]
    modId="embeddium"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chaosket]]
    modId="oculus"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chaosket]]
    modId="craft_tweaker"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chaosket]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

